### ISSUE TITLE
do i need to have brave browser?

### ISSUE THREAD

**Issue by nameplzwork** [alexlwn123/Chesscup-hack#1]
i tried running script.js using node.js(i have dotnev and selenium-webdriver) and it says this: 
WebDriverError: unknown error: no chrome binary at /Applications/Brave Browser.app/Contents/MacOS/Brave Browser
    at Object.throwDecodedError (C:\Users\*****\node_modules\selenium-webdriver\lib\error.js:524:15)
    at parseHttpResponse (C:\Users\*****\node_modules\selenium-webdriver\lib\http.js:601:13)
    at Executor.execute (C:\Users\*****\node_modules\selenium-webdriver\lib\http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  remoteStacktrace: 'Backtrace:\n' +
    '\tGetHandleVerifier [0x0094A813+48355]\n' +
    '\t(No symbol) [0x008DC4B1]\n' +
    '\t(No symbol) [0x007E5358]\n' +
    '\t(No symbol) [0x00801A33]\n' +
    '\t(No symbol) [0x00800579]\n' +
    '\t(No symbol) [0x00830C55]\n' +
    '\t(No symbol) [0x0083093C]\n' +
    '\t(No symbol) [0x0082A536]\n' +
    '\t(No symbol) [0x008082DC]\n' +
    '\t(No symbol) [0x008093DD]\n' +
    '\tGetHandleVerifier [0x00BAAABD+2539405]\n' +
    '\tGetHandleVerifier [0x00BEA78F+2800735]\n' +
    '\tGetHandleVerifier [0x00BE456C+2775612]\n' +
    '\tGetHandleVerifier [0x009D51E0+616112]\n' +
    '\t(No symbol) [0x008E5F8C]\n' +
    '\t(No symbol) [0x008E2328]\n' +
    '\t(No symbol) [0x008E240B]\n' +
    '\t(No symbol) [0x008D4FF7]\n' +
    '\tBaseThreadInitThunk [0x752A00C9+25]\n' +
    '\tRtlGetAppContainerNamedObjectPath [0x76EC7B4E+286]\n' +
    '\tRtlGetAppContainerNamedObjectPath [0x76EC7B1E+238]\n'
}
so my question is, do i have to install brave browser for the file to work?

**Comment by nameplzwork** [comment]
do i need to also put my login details in the code or something?

**Comment by alexlwn123** [comment]
Assuming you figured it out.

In case you haven't, you need to swap out the binary path for your environment. It needs to point to the application file for 
your browser
