### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by ori64TS** [alexlwn123/Chesscup-hack#4]
when i lunce the file in the cmd the chrom opening with the website but then it just stuck on the start manu and when i prees start nothing happen this is the eror:

C:\Users\Ori\scripts\Chesscup-hack-main\Chesscup-hack-main>node script.js
Applicable driver not found; attempting to install with Selenium Manager (Beta)
The version of chrome cannot be detected. Trying with latest driver version

DevTools listening on ws://127.0.0.1:63913/devtools/browser/7342b37a-878c-478c-be00-d9aa3c09ffb5
[2772:21212:0628/195129.494:ERROR:cert_issuer_source_aia.cc(34)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

C:\Users\Ori\node_modules\selenium-webdriver\lib\error.js:524
    let err = new ctor(data.message)
              ^

ElementNotInteractableError: element not interactable
  (Session info: chrome=114.0.5735.198)
    at Object.throwDecodedError (C:\Users\Ori\node_modules\selenium-webdriver\lib\error.js:524:15)
    at parseHttpResponse (C:\Users\Ori\node_modules\selenium-webdriver\lib\http.js:601:13)
    at Executor.execute (C:\Users\Ori\node_modules\selenium-webdriver\lib\http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Driver.execute (C:\Users\Ori\node_modules\selenium-webdriver\lib\webdriver.js:745:17)
    at async init (C:\Users\Ori\scripts\Chesscup-hack-main\Chesscup-hack-main\script.js:110:3)
    at async main (C:\Users\Ori\scripts\Chesscup-hack-main\Chesscup-hack-main\script.js:224:3) {
  remoteStacktrace: 'Backtrace:\n' +
    '\tGetHandleVerifier [0x011DA813+48355]\n' +
    '\t(No symbol) [0x0116C4B1]\n' +
    '\t(No symbol) [0x01075220]\n' +
    '\t(No symbol) [0x010A1846]\n' +
    '\t(No symbol) [0x01099F5C]\n' +
    '\t(No symbol) [0x010BA73C]\n' +
    '\t(No symbol) [0x01099A36]\n' +
    '\t(No symbol) [0x010BAA94]\n' +
    '\t(No symbol) [0x010CC922]\n' +
    '\t(No symbol) [0x010BA536]\n' +
    '\t(No symbol) [0x010982DC]\n' +
    '\t(No symbol) [0x010993DD]\n' +
    '\tGetHandleVerifier [0x0143AABD+2539405]\n' +
    '\tGetHandleVerifier [0x0147A78F+2800735]\n' +
    '\tGetHandleVerifier [0x0147456C+2775612]\n' +
    '\tGetHandleVerifier [0x012651E0+616112]\n' +
    '\t(No symbol) [0x01175F8C]\n' +
    '\t(No symbol) [0x01172328]\n' +
    '\t(No symbol) [0x0117240B]\n' +
    '\t(No symbol) [0x01164FF7]\n' +
    '\tBaseThreadInitThunk [0x769700C9+25]\n' +
    '\tRtlGetAppContainerNamedObjectPath [0x77497B4E+286]\n' +
    '\tRtlGetAppContainerNamedObjectPath [0x77497B1E+238]\n'
}

Node.js v20.3.1

**Comment by alexlwn123** [comment]
That's basically saying it can't find a DOM element to click on. It's on the dark mode toggle. Try commenting out the line

I'm guessing your browser is presenting the website slightly differently from mine. 
Here's a couple of things to try:  
1. Comment out this line -->  `await driver.findElement(webdriver.By.xpath('//*[@id="darkModeToggler"]')).click();`
2. If it still breaks, try using Brave Browser.

If that doesn't work, I think you're on your own, as I can't control your environment. :(
