### ISSUE TITLE
error(alr did .env thing)

### ISSUE THREAD

**Issue by nameplzwork** [alexlwn123/Chesscup-hack#5]
DevTools listening on ws://127.0.0.1:59357/devtools/browser/e5264760-a92f-4daf-bc64-38f33d107b80
[4984:26712:0628/215833.675:ERROR:device_event_log_impl.cc(222)] [21:58:33.675] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
C:\Users*****\node_modules\selenium-webdriver\lib\webdriver.js:929
new error.TimeoutError(
^

TimeoutError: Waiting for element to be located By(xpath, //[@id="testpng"]/div[1]/div/div[1]/div[2]/div[3])
Wait timed out after 15132ms
at C:\Users****\node_modules\selenium-webdriver\lib\webdriver.js:929:17
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
remoteStacktrace: ''
}

**Comment by alexlwn123** [comment]
The error suggests that your website is structured slightly different from mine. I'm thinking it's probably due to your operating system or browser.

I use MacOS and Brave browser. That's the only configuration I've tested.

**Comment by alexlwn123** [comment]
I updated the readme with this information. Thanks!
