### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by ori64TS** [alexlwn123/Chesscup-hack#9]
everything is working exept the pawn promotion like it cant promote the pawn and its just stuck can u fix it u should make a function that open the menu to what to promote and then clike but this is only my opinion

https://github.com/alexlwn123/Chesscup-hack/assets/117532209/71738505-de65-4d80-9a02-bcd8a604623f

**Comment by alexlwn123** [comment]
Yeah, I'm aware... I'll fix it one of these days. Thanks

**Comment by alexlwn123** [comment]
@ori64TS Pawn promotion support added!
